### ISSUE TITLE
[Idea]: Support for getting latest frame from a screenrecord/framebuffer

### ISSUE THREAD

**Issue by ninjatall12** [abhiTronix/deffcode#33]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/deffcode/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/deffcode/issues) and found nothing related to my idea.
- [X] I have read the [Documentation](https://abhitronix.github.io/deffcode/latest) and it doesn't mention anything about my idea.
- [X] To my best knowledge, my idea wouldn't break something for other users.

### Describe your Idea

ability to return latest frame from screenrecord/frame buffer so that it can used for object/color detection

### Use Cases

Allow ability for object tracking/color tracking within a video at much higher fps than using open cv or alternatives

**Comment by abhiTronix** [comment]
> ability to return latest frame from screenrecord/frame buffer so that it can used for object/color detection

@ninjatall12 Hi, could you please elaborate what you mean by this?

**Comment by ninjatall12** [comment]
so basically i want a function similar to sct.grab() which returns the latest frame without needing to iterate through the generator object

**Comment by abhiTronix** [comment]
> so basically i want a function similar to sct.grab() in mss which returns the latest frame without needing to iterate through the generator object for example in here

@ninjatall12 There's no buffer, the FFmpeg serializes the frames and deffcode captures it and generator makes it available. Simple as that. I'm closing this issue as it is not applicable here
