### ISSUE TITLE
[Question]: Add ffmpeg creationflag in Deffcode Library

### ISSUE THREAD

**Issue by nidhi-jha01** [abhiTronix/deffcode#42]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/deffcode/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/deffcode/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/deffcode/latest) and found nothing related to my problem.

### Describe your Question

I am using FFdecoder to read video files in my application. I am creating an MSI(Windows Exe)  of my application. While calling the method having FFdecoder, I experienced a terminal window for ffmpeg.exe coming up multiple times, creating an issue for my application. I have tried verbose = False and used CREATENOWINDOW as creationflags = sp.CREATE_NO_WINDOW) in popen. Can you help with this Issue.
<img width="884" alt="ffmpegpopup" src="https://github.com/abhiTronix/deffcode/assets/78956652/656af708-922f-4014-ad45-731c74550c5e">

### DeFFcode Version

0.2.5

### Python version

3.9

### Operating System version

Windows 11

**Comment by abhiTronix** [comment]
Good news. There's a pull request: https://github.com/abhiTronix/vidgear/pull/375 that might work for deffcode too.

**Comment by abhiTronix** [comment]
**This issue is fixed in commit https://github.com/abhiTronix/deffcode/commit/84e8af1d7c8ef082d3d0ed92190f6dcd14ae3622**
