### ISSUE TITLE
[Question]: most performant way to decode many small videos

### ISSUE THREAD

**Issue by KDeser** [abhiTronix/deffcode#43]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/deffcode/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/deffcode/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/deffcode/latest) and found nothing related to my problem.

### Describe your Question

Is there a way to reuse a decoder for multiple videos to reduce the delay between each video? It's actually taking longer to instantiate the decoder object for each video than it does to generate and analyze the frames. There are many thousands of these videos and they are individually only ~100 frames in length. 

Here's a (simplified) version of my code.

Thanks!

### Python Code(Optional)

```python
from deffcode import FFdecoder
for video_path in video_paths:
    # ~0.4 seconds
    decoder = FFdecoder(
            video_path, frame_format="bgr24"
        ).formulate()
    # ~0.2 seconds
    frames = [f for f in decoder.generateFrame()]
    # ~0.1 seconds
    analyze_frames(frames)
```

### DeFFcode Version

0.2.5

### Python version

3.9

### Operating System version

Windows 10

**Comment by abhiTronix** [comment]
@KDeser Thank you for you issue. Right now, the current structuring of DeFFcode library is more focused on sanitizing the input parameters and source provide for error-free pipeline, and goes through series of methods to check them on initialization. So the performance will not be great for short videos but rather more tuned for longer duration videos. I'll recommend using other options such as PIL or OpenCV for this purpose.
