### ISSUE TITLE
[Question]: OPen multiple Same Camera, ValueError: Invalid source with no decodable audio or video stream provided. Aborting!

### ISSUE THREAD

**Issue by GavinJIAW** [abhiTronix/deffcode#47]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/deffcode/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/deffcode/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/deffcode/latest) and found nothing related to my problem.

### Describe your Question

OPen multiple Same Camera, ValueError: Invalid source with no decodable audio or video stream provided. Aborting!

### Terminal log output(Optional)

```shell
ValueError: Invalid source with no decodable audio or video stream provided. Aborting!
```

### Python Code(Optional)

```python
decoder = FFdecoder("0", frame_format="bgr24",custom_ffmpeg="./ffmpeg/bin", verbose=True,**ffparams).formulate()
decoder = FFdecoder("1", frame_format="bgr24",custom_ffmpeg="./ffmpeg/bin", verbose=True,**ffparams).formulate()
decoder = FFdecoder("3", frame_format="bgr24",custom_ffmpeg="./ffmpeg/bin", verbose=True,**ffparams).formulate()
```

### DeFFcode Version

0.2.3

### Python version

3.10

### Operating System version

windows

**Comment by abhiTronix** [comment]
`ValueError: Invalid source with no decodable audio or video stream provided. Aborting!`

@GavinJIAW This error means that one of the `source` value is invalid, meaning there's no device at "0" or "1" or "3" index, check logs to get more insight. And it is perfectly fine to open multiple cameras, as long as your system allows it.
